# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'HelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorld
  pod 'DynamsoftDocumentNormalizer','2.0.10'
  pod 'DynamsoftCaptureVisionRouter','2.0.10'
  pod 'DynamsoftCameraEnhancer','4.0.0'
  pod 'DynamsoftUtility','1.0.10'

end
