# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'AutoNormalizeObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoNormalizeObjc
  pod 'DynamsoftDocumentNormalizerBundle','2.2.1101'

end
