# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'AutoNormalize' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoNormalize
  pod 'DynamsoftCore','3.2.10'
  pod 'DynamsoftImageProcessing','2.2.10'
  pod 'DynamsoftLicense','3.2.10'
  pod 'DynamsoftDocumentNormalizer','2.2.10'
  pod 'DynamsoftCaptureVisionRouter','2.2.11'
  pod 'DynamsoftCameraEnhancer','4.2.0'
  pod 'DynamsoftUtility','1.2.10'

end
